#!/bin/sh
#
# Copyright 2019, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#

echo "Testing arping on virtual interface:"
arping 192.168.1.2 -c 5 -w 2
# Success code for arping: 0 (arping returns non-zero value if packet count and timeout is not met)
if [ $? -eq 0 ]
then
    echo "arping test was successful"
else
    echo "arping test failed"
fi
