#!/bin/sh
#
# Copyright 2019, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

echo "Testing ping on virtual interface:"
ping 192.168.1.2 -v -c 5 -W 2
# Success code for Ping: 0 (Ping returns non-zero value if packet count and timeout is not met)
if [ $? -eq 0 ]
then
    echo "Ping test was successful"
else
    echo "Ping test failed"
fi
