#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#


apps-$(CONFIG_APP_CAMKES_VM) += vm
vm: libsel4 libmuslc libsel4platsupport libsel4muslccamkes libsel4camkes libsel4sync libsel4debug libsel4bench libsel4simple libsel4allocman libsel4arm-vmm libsel4vka \
            libsel4vspace libelf libsel4utils libutils libsel4simple-default libcpio
