#!/bin/sh

dev=eth0
vid1=100
vid2=200
type="unidirectional"
node=""

# Help menu
show_help() {
    echo "Makes a node silently forward vlan packets from one network to another using vanilla linux on a remote host"
    echo
    echo "Usage: $0 [options] node dev vid1 vid2"
    echo
    echo "Options:"
    echo "  --bi,    Allow bidirectional flow"
    echo "  --uni,   Allow unidirectional flow (default)"
    echo "  --dev,   Specify the device to apply this flow to"
    echo "  --vid1,  Specify the vlan id to forward from"
    echo "  --vid2,  Specify the vlan id to forward to"
    echo "  --help,  Print this help menu"
}


# Parse CLI flag arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --bi)
        type="bidirectional"
        shift
        ;;
    --uni)
        type="unidirectional"
        shift
        ;;
    --dev)
        shift
        dev="$1"
        shift
        ;;
    --vid1)
        shift
        vid1="$1"
        shift
        ;;
    --vid2)
        shift
        vid2="$1"
        shift
        ;;
    --node)
        shift
        node="$1"
        shift
        ;;
    --help)
        show_help
        exit 0
        ;;
  esac
done


# Parse positional arguments
if [[ -z $node && $# -ge 1 ]]; then
    node="$1"
    shift
fi

if [[ -z $dev&& $# -ge 1 ]]; then
    bridge="$1"
    shift
fi
if [[ -z $vid1 && $# -ge 1 ]]; then
    vid1="$1"
    shift
fi
if [[ -z $vid2 && $# -ge 1 ]]; then
    vid2="$1"
    shift
fi


# Verify we have all the arguments
if [[ -z $node || -z $dev || -z $vid1 || -z $vid2 ]]; then
    echo "Error: node, dev, vid1, and vid2 are required."
    show_help
    exit 1
fi


# Create VLAN interfaces
echo sshpass -p "root" dbclient -y "$node" "ip link add link $dev name $dev.$vid1 type vlan id $vid1"
echo sshpass -p "root" dbclient -y "$node" "ip link add link $dev name $dev.$vid2 type vlan id $vid2"
sshpass -p "root" dbclient -y "$node" "ip link add link $dev name $dev.$vid1 type vlan id $vid1"
sshpass -p "root" dbclient -y "$node" "ip link add link $dev name $dev.$vid2 type vlan id $vid2"


# Bring up interfaces
echo sshpass -p "root" dbclient -y "$node" "ip link set $dev up"
echo sshpass -p "root" dbclient -y "$node" "ip link set $dev.$vid1 up"
echo sshpass -p "root" dbclient -y "$node" "ip link set $dev.$vid2 up"
sshpass -p "root" dbclient -y "$node" "ip link set $dev up"
sshpass -p "root" dbclient -y "$node" "ip link set $dev.$vid1 up"
sshpass -p "root" dbclient -y "$node" "ip link set $dev.$vid2 up"


# Create a bridge and add interfaces
echo sshpass -p "root" dbclient -y "$node" "ip link add name br$vid1$vid2 type bridge"
echo sshpass -p "root" dbclient -y "$node" "ip link set br$vid1$vid2 up"
echo sshpass -p "root" dbclient -y "$node" "ip link set $dev.$vid1 master br$vid1$vid2"
echo sshpass -p "root" dbclient -y "$node" "ip link set $dev.$vid2 master br$vid1$vid2"
sshpass -p "root" dbclient -y "$node" "ip link add name br$vid1$vid2 type bridge"
sshpass -p "root" dbclient -y "$node" "ip link set br$vid1$vid2 up"
sshpass -p "root" dbclient -y "$node" "ip link set $dev.$vid1 master br$vid1$vid2"
sshpass -p "root" dbclient -y "$node" "ip link set $dev.$vid2 master br$vid1$vid2"


# Set up forwarding rules
echo sshpass -p "root" dbclient -y "$node" "iptables -A FORWARD -i $dev.$vid1 -o $dev.$vid2 -j ACCEPT"
sshpass -p "root" dbclient -y "$node" "iptables -A FORWARD -i $dev.$vid1 -o $dev.$vid2 -j ACCEPT"
# sshpass -p "root" dbclient -y "$node" "iptables -A FORWARD -i eth0.20 -o eth0.10 -j ACCEPT"

# Enfore unidirectionality to prevent broadcast storms
echo sshpass -p "root" dbclient -y "$node" "iptables -A FORWARD -i $dev.$vid2 -o $dev.$vid1 -j DROP"
sshpass -p "root" dbclient -y "$node" "iptables -A FORWARD -i $dev.$vid2 -o $dev.$vid1 -j DROP"




# echo sshpass -p "root" dbclient -y "$node" "iptables -t nat -A PREROUTING -i $dev.$vid1 -j DNAT --to-destination $dev.$vid2"
# echo sshpass -p "root" dbclient -y "$node" "iptables -A FORWARD -i $dev.$vid1 -o $dev.$vid2 -j ACCEPT"
# echo sshpass -p "root" dbclient -y "$node" "iptables -A FORWARD -i $dev.$vid2 -o $dev.$vid1 -m state --state ESTABLISHED,RELATED -j ACCEPT"
# sshpass -p "root" dbclient -y "$node" "iptables -t nat -A PREROUTING -i $dev.$vid1 -j DNAT --to-destination $dev.$vid2"
# sshpass -p "root" dbclient -y "$node" "iptables -A FORWARD -i $dev.$vid1 -o $dev.$vid2 -j ACCEPT"
# sshpass -p "root" dbclient -y "$node" "iptables -A FORWARD -i $dev.$vid2 -o $dev.$vid1 -m state --state ESTABLISHED,RELATED -j ACCEPT"


# # Add the reverse direction if necessary
# if [ "$type" = "bidirectional" ]; then
#     sshpass -p "root" dbclient -y "$node" "iptables -t nat -A PREROUTING -i $dev.$vid2 -j DNAT --to-destination $dev.$vid1"
#     sshpass -p "root" dbclient -y "$node" "iptables -A FORWARD -i $dev.$vid2 -o $dev.$vid1 -j ACCEPT"
#     sshpass -p "root" dbclient -y "$node" "iptables -A FORWARD -i $dev.$vid1 -o $dev.$vid2 -m state --state ESTABLISHED,RELATED -j ACCEPT"
# fi

