#!/bin/sh
### BEGIN INIT INFO
# Provides:          ping_test
# Required-Start:    $networking
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: Configure virtio-net device
### END INIT INFO

#
# Copyright 2019, Data61, CSIRO (ABN 41 687 119 230)
# Copyright 2024, DornerWorks
#
# SPDX-License-Identifier: BSD-2-Clause
#

echo "Testing ping on virtual interface:" > /dev/console

# Petalinux 2022.1 doesn't seem to like the /etc/network/interfaces file
eth0_ip="192.168.1.1"
ifconfig eth0 $eth0_ip

ping 192.168.1.2 -v -c 5 -W 2
# Success code for Ping: 0 (Ping returns non-zero value if packet count and timeout is not met)
if [ $? -eq 0 ]
then
    echo "Ping test was successful" > /dev/console
else
    echo "Ping test failed" > /dev/console
fi
