#!/bin/sh
#
# Copyright 2019, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#

echo "HERE"

mknod /dev/ttyAMA0 c 204 64

#insmod /lib/modules/4.14.87/kernel/drivers/vmm/connection.ko

